/**
 * Standard OpenUI section (`openui`).
 *
 * A section file that starts with an `// @openui "Title"` directive is a plain
 * OpenUI Lang program written against the standard `@openuidev/react-ui`
 * component library (Card, Tabs, Table, charts, Accordion, Steps, …) instead
 * of the Loom section library:
 *
 *   // @openui "Pricing" "Pick a plan"
 *   root = Card([header, tabs])
 *   header = CardHeader("Plans", "Compare what you get")
 *   …
 *
 * The directive carries the section title and optional heading; everything
 * after it is stored verbatim as the section's `source` and rendered with
 * OpenUI's `<Renderer>`.
 *
 * `schema.json` / `spec.json` / `dark-theme.json` snapshot the standard
 * library (generated by `npm run openui:gen`) so parsing and editor tooling
 * don't have to import react-ui; only the lazily loaded renderer does.
 */
import type { ComponentGroup, LibraryJSONSchema } from '@openuidev/lang-core'
import schema from './schema.json'
import spec from './spec.json'

export const OPENUI_SECTION_TYPE = 'openui'

/** JSON Schema of the standard OpenUI library (`openuiLibrary.toJSONSchema()`). */
export const standardOpenUISchema = schema as unknown as LibraryJSONSchema

export interface StandardOpenUISpec {
  root: string
  /** Positional signature and description of every component. */
  components: Record<string, { signature: string; description: string }>
  componentGroups: ComponentGroup[]
}

/** Signatures and groups of the standard OpenUI library. */
export const standardOpenUISpec = spec as StandardOpenUISpec

export interface OpenUIDirective {
  title: string
  heading?: string
  /** 1-based line of the directive. */
  line: number
}

const DIRECTIVE = /^[ \t]*\/\/[ \t]*@openui(?![\w-])(.*)$/
const STRING = /"(?:[^"\\\n]|\\.)*"/g

function firstContentLine(lines: string[]): number {
  return lines.findIndex((l) => l.trim() !== '')
}

/** Read the `// @openui "Title" ["Heading"]` directive on the first non-blank line. */
export function readOpenUIDirective(source: string): OpenUIDirective | null {
  const lines = source.split('\n')
  const index = firstContentLine(lines)
  const match = index < 0 ? null : DIRECTIVE.exec(lines[index])
  if (!match) return null
  const args = [...match[1].matchAll(STRING)].map((m) => {
    try {
      return JSON.parse(m[0]) as string
    } catch {
      return m[0].slice(1, -1)
    }
  })
  return { title: args[0] ?? '', heading: args[1] || undefined, line: index + 1 }
}

/** True when a section source is a standard OpenUI program. */
export function isOpenUISource(source: string): boolean {
  return readOpenUIDirective(source) !== null
}

/** The OpenUI program of a directive file (everything after the directive line). */
export function openUIProgramOf(source: string): string {
  const lines = source.split('\n')
  const index = firstContentLine(lines)
  return lines.slice(index + 1).join('\n').replace(/^\s*\n/, '').trimEnd()
}

/** Print an `openui` section file: directive line followed by the program. */
export function printOpenUISection(program: string, title: string, heading?: string): string {
  const args = [JSON.stringify(title), ...(heading ? [JSON.stringify(heading)] : [])].join(' ')
  return `// @openui ${args}\n${program.trim()}\n`
}
