/**
 * Contents of the generated Loom OpenUI schema files (scripts/gen-oui-schema.ts),
 * keyed by path from the repository root. Shared with the unit test that
 * keeps the committed files fresh.
 */
import { getLoomOUIJSONSchema, getLoomOUIPrompt } from './library'

const HEADER = `<!-- Generated by \`npm run oui:schema\` from the Loom OpenUI library. Do not edit. -->\n\n`

export function ouiSchemaFiles(): Record<string, string> {
  return {
    'schemas/oui/loom-oui.prompt.md': `${HEADER}${getLoomOUIPrompt()}\n`,
    'schemas/oui/loom-oui.schema.json': `${JSON.stringify(getLoomOUIJSONSchema(), null, 2)}\n`,
  }
}
